name: windows_calculator_mac

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pygame pyinstaller

    - name: Build Mac App
      run: |
        pyinstaller \
        --onedir \
        --windowed \
        --icon=calculator/device.icns \
        --add-data "calculator/*.png:." \
        calculator/calculate.py

    - name: Zip Mac build
      run: |
        cd dist
        zip -r Calculator_Mac_${{ github.ref_name }}.zip calculate.app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-mac
        path: dist/Calculator_Mac_${{ github.ref_name }}.zip
